# Site settings
title: Software Craftmanship
email: sammuel.septiano@gmail.com
url: https://github.com/jeromelachaud/freelancer-theme
description: "Graduated from Computer Science major with some professional experiences in the field of Software Engineering especially in Web and Mobile Development at startup and enterprise level company with various industries like Financial Technology, HRIS, POS, Logistic, Sales, Healthcare, etc. since 2017. Experienced in Web and Mobile Development using Kotlin, JAVA, Flutter, .NET/.NET Core, and PHP."
keywords: "software-development,mobile-development,project-management"
skills: "Software Engineering - Project Management"
meta_author: Septiano Samuel

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Find Me
  credits: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/samseptiano
  - title: linkedin
    url: https://linkedin.com/in/samseptiano
  - title: github
    url: https://github.com/samseptiano
  - title: whatsapp
    url: https://wa.me/6283871979960


# Postal address (add as many lines as necessary)
address:
  - line: Bekasi
  - line: West Java, Indonesia 17116

# Credits content
# credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Contact me</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
